### ISSUE TITLE
Backport all changes from release branch

### ISSUE THREAD

**Issue by rakita** [bluealloy/revm#1896]
List of changes
- [x] 2c9290a1 - (origin/release/v55) fix(op): add operator fee scalar scaling factor on refund (#2050) (2 days ago) <Aurélien> 
- [x] 14c5cc1d - (origin/release/v52) feat: Include EIP7702 address for extcodecopy (#2016) (11 days ago) <Elijah Hampton> 
- [x] 6d907985 - fix(op): isthmus compilation (#2022) (2 weeks ago) <rakita>
- [x] feat(optimism): implement BLS precompiles for isthmus https://github.com/bluealloy/revm/pull/2000 
- [x] 9dd9f9ea - chore: optimize tx l1 fetches (#1967) (2 hours ago) <rakita>
- [x] 226f0591 - feat: handle isthmus operator fee (#1960) (3 days ago) <Aurélien>
- [x] 811bc7d8 - fix: add proper part to devnet5 tests (10 days ago) <rakita>
- [x] d6b90a00 - (tag: v51, origin/release/v51) bump: alloy core and use PrimitiveSignature (#1954) (11 days ago) <rakita>
- [x] 66ee5069 - feat: blst reprice, remove g1/g2 mul, eest test bump (#1951) (12 days ago) <rakita>
- [x] 0c69ccd9 - chore: eip7702 chainid u256 change (#1950) (12 days ago) <rakita>
- [x] e30fe19c - feat: add Isthmus spec (#1948) (13 days ago) <Aurélien>
- [x] 12b0babc - (origin/release/v51) feat: eip7691 fraction update (#1900) (35 hours ago) <rakita>
- [x] d8ca097d - feat: apply latest EIP-7702 changes (#1850) (2 days ago) <Arsenii Kulikov>
- [x] 4e00f32d - EIP-7742: Uncouple blob count between CL and EL (#1899) (3 days ago) <rakita>
- [x] 6882e221 - feat(Prague): EIP-7623 Increase Calldata Cost (#1744) (3 days ago) <Roman Krasiuk>
- [x] a0024590 - (origin/rakita/l1block_cleanup_to_v512) chore: refactor L1BlockInfo::tx_estimated_size_fjord (#1862) (3 weeks ago) <Hai | RISE>
- [x] 4f762914 - [v50] perf: remove unneeded clones (#1863) (3 weeks ago) <Hai | RISE>
- [x] 9519b113 - perf: Add static Optimism precompiles for Fjord & Granite (#1864) (3 weeks ago) <Hai | RISE> 
- [x] 9dcd87c2 -  perf(precompile): use secp256k1 global context for ecrecover  (#1845) (5 weeks ago) <Dan Cline>
- [x] 346aa013 - Osaka Activation (release_49 branch) (#1835) (6 weeks ago) <Danno Ferrin>
- [x] fc1556f7 - feat: Add holocene to OP spec (#1794) (3 months ago) <cody-wang-cb>
- [x] 89b65e1e - Test l1 gas used fjord (#1749) (3 months ago) <Emilia Hane>
- [x] 32f357fa - fix(inspector): always call selfdestruct if entry is made (#1746) (3 months ago) <Delweng>
- [x] fa5650ee - Add test for `revm::optimism::L1BlockInfo::calculate_tx_l1_cost_fjord` (#1743) (3 months ago) <Emilia Hane>

Spans multiple versions:
- [x] Check dependency versions.
- [x] Backport changelogs from v44 onwards

**Comment by rakita** [comment]
Done, all commits backported
